server:
  port: 8872
spring:
  application:
    name: SrvProvider
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eurekasvr1:8861/eureka/,http://eurekasvr2:8862/eureka/

